# get shiny serves plus tidyverse packages image
FROM rocker/shiny:4.2

# system libraries of general use
RUN apt-get update
RUN apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    gdebi-core \
    xtail \
    wget \
    curl net-tools vim \
    libudunits2-dev \
    libgdal-dev libgeos-dev libproj-dev
# install R packages required
# (change it depending on the packages you need)

RUN R -q -e "install.packages(c('shiny'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinydashboard'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('dplyr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('lubridate'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('tidyverse'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('plotly'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinyWidgets'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('stringr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('tidyr'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('DT'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('shinymanager'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('gotop'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('highcharter'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('glue'), repos = 'http://cloud.r-project.org')"
RUN R -q -e "install.packages(c('writexl'), repos = 'http://cloud.r-project.org')"

#docker build --tag=my-shiny-app-packages:v1 -f Dockerfile-base .
